include ../../Makefile.inc

FLAGS2 = -fstrength-reduce -fomit-frame-pointer -finline-functions -nostdinc -fno-builtin -I../../include/applications

all:
	$(GCC) $(AFLAGS) -c -o ../../Build/shell.o shell.c
